- name: Kafka connect create directories
  file:
    state: directory
    path: "{{ item }}"
    mode: 0750
    owner: "{{ kafka_user }}"
    group: "{{ kafka_group }}"
  with_items:
    - "{{ kafka_connect_etc_dir }}"
    - "{{ kafka_connect_data_dir }}"
    - "{{ kafka_connect_log_dir }}"

- name: Create kafka connect configs
  template:
    src: connect-distributed.properties.j2
    dest: "{{ kafka_connect_etc_dir }}/connect-distributed.properties"
    mode: 0400
    owner: "{{ kafka_user }}"
    group: "{{ kafka_group }}"

- name: Copy Log4j Properties
  template:
    src: log4j.properties.j2
    dest: "{{ kafka_connect_etc_dir }}/log4j.properties"
    mode: 0400
    owner: "{{ kafka_user }}"
    group: "{{ kafka_group }}"
