#- name: zookeeper Provisioning
#  hosts: zookeeper
#  gather_facts: no
#  tags:
#    - zookeeper
#  tasks:
#  - import_role:
#      name: confluent.zookeeper

- name: Server Setup
  become_user: {{ confluent_user }}
  hosts: all
  gather_facts: no
  tags:
    - common
  tasks:
    - import_role:
        name: confluent.common
