all:
  vars:
    ansible_connection: ssh
    ansible_ssh_user: vcs_kafka
zookeeper:
  hosts:
    192.168.104.5:

kafka_broker:
  hosts:
   192.168.104.4:

kafka_connect:
  hosts:  
    192.168.104.4:
