all:
  vars:
    ansible_connection: ssh
    ansible_ssh_user: vcs_kafka
zookeeper:
  hosts:
    10.0.136.223:
    10.0.132.136:
    10.0.129.30:

kafka_broker:
  hosts:
    10.0.135.180:
    10.0.140.133:
    10.0.141.90:

kafka_connect:
  hosts:
    10.0.2.4
