all:
  vars:
  #   ansible_connection: ssh
  #   ansible_ssh_user: sba
zookeeper:
  hosts:
    localhost:

kafka_broker:
  hosts:
    localhost:

kafka_connect:
  hosts:  
    localhost:

kafka_ccc:
  hosts:
    localhost:
