- hosts:
    - kafka
  name: Deploy Kafka and Zookeeper configs
  become_user: "{{ confluent_user }}"

  tasks:
    - name: download confluent tar ball
      get_url:
        url: http://packages.confluent.io/archive/5.3/confluent-5.3.1-2.12.tar.gz
        dest: "{{ confluent_home }}"
