confluent_user: vcsgscds
confluent_group: vcsgscds
confluent_home: /opt/vcs/pds
confluent_appdir: "{{ confluent_home }}/confluent"
confluent_tar_version: confluent-5.3.1-2.12
confluent_version: confluent-5.3.1
confluent_bundle_path: "{{ confluent_home }}/{{ confluent_version }}"
tar_location: "/home/vcsgscds/"

confluent_license: ""

confluent_etc_dir: "{{ confluent_appdir }}/etc"
confluent_log_dir: "{{ confluent_appdir }}/log"
confluent_data_dir: "{{ confluent_appdir }}/dataDir"

zookeeper:
zk_port: 2181
zk_user: vcsgscds
zk_group: vcsgscds
zk_bin_dir: "{{ confluent_appdir }}/bin"
zk_etc_dir: "{{ confluent_etc_dir }}/zk"
zk_log_dir: "{{ confluent_log_dir }}/zk"
zk_data_dir: "{{ confluent_data_dir }}/zk"

kafka_broker:
kafka_port: 9092
kafka_user: vcsgscds
kafka_group: vcsgscds
kafka_bin_dir: "{{ confluent_appdir }}/bin"
kafka_etc_dir: "{{ confluent_etc_dir }}/kafka"
kafka_data_dir: "{{ confluent_data_dir }}/kafka"
kafka_log_dir: "{{ confluent_log_dir }}/kafka"

kafka_connect:
confluent_plugin_dir: "{{ confluent_appdir }}/plugins"
kafka_connect_etc_dir: "{{ confluent_etc_dir }}/kafka_connect"
kafka_connect_data_dir: "{{ confluent_data_dir }}/kafka_connect"
kafka_connect_log_dir: "{{ confluent_log_dir }}/kafka_connect"
