confluent_user: sba
confluent_group: staff
confluent_home: /Users/sba/ConfluentInstall
confluent_appdir: "{{ confluent_home }}/confluent"
confluent_package_url: https://packages.confluent.io/archive/6.2/confluent-6.2.0.tar.gz
confluent_tar_version: confluent-6.2.0
confluent_version: confluent-6.2.0
confluent_bundle_path: "{{ confluent_home }}/bundles/{{ confluent_version }}"
tar_location: "/Users/sba/tmp"

confluent_license: ""

confluent_etc_dir: "{{ confluent_appdir }}/etc"
confluent_log_dir: "{{ confluent_appdir }}/log"
confluent_data_dir: "{{ confluent_appdir }}/dataDir"

zookeeper:
zk_port: 2181
zk_user: sba
zk_group: staff
zk_bin_dir: "{{ confluent_appdir }}/bin"
zk_etc_dir: "{{ confluent_etc_dir }}/zk"
zk_log_dir: "{{ confluent_log_dir }}/zk"
zk_data_dir: "{{ confluent_data_dir }}/zk"

kafka_broker:
kafka_port: 9092
kafka_user: sba
kafka_group: staff
kafka_bin_dir: "{{ confluent_appdir }}/bin"
kafka_etc_dir: "{{ confluent_etc_dir }}/kafka"
kafka_data_dir: "{{ confluent_data_dir }}/kafka"
kafka_log_dir: "{{ confluent_log_dir }}/kafka"

kafka_connect:
confluent_plugin_dir: "{{ confluent_appdir }}/plugins"
kafka_connect_etc_dir: "{{ confluent_etc_dir }}/kafka_connect"
kafka_connect_data_dir: "{{ confluent_data_dir }}/kafka_connect"
kafka_connect_log_dir: "{{ confluent_log_dir }}/kafka_connect"
kafka_user_defined_plugins_dir : "{{ confluent_appdir }}/kafka_user_defined_plugins"

ksql:
ksql_port: 8088
ksql_user: sba
ksql_group: staff
ksql_bin_dir: "{{ confluent_appdir }}/bin"
ksql_etc_dir: "{{ confluent_etc_dir }}/ksql"
ksql_log_dir: "{{ confluent_log_dir }}/ksql"
ksql_data_dir: "{{ confluent_data_dir }}/ksql"