- name: Generic folder structure creation
  file:
    state: directory
    path: "{{ item }}"
    mode: "0755"
    owner: "{{ confluent_user }}"
    group: "{{ confluent_group }}"
  with_items:
    - "{{ confluent_appdir }}"
    - "{{ confluent_appdir }}/bundles"
    - "{{ confluent_appdir }}/etc"

- name: Download the tar ball from the confluent website
  unarchive:
    src: "{{ tar_location }}/{{ confluent_version }}.tar"
    dest: "{{ confluent_appdir }}/bundles/"
