- name: Kafka Broker create directories
  file:
    state: directory
    path: "{{ item }}"
    mode: 0750
    owner: "{{ kafka_user }}"
    group: "{{ kafka_group }}"
  with_items:
    - "{{ kafka_etc_dir }}"
    - "{{ kafka_data_dir }}"
    - "{{ kafka_log_dir }}"

- name: Create kafka broker configs
  template:
    src: server.properties.j2
    dest: "{{ kafka_etc_dir }}/server.properties"
    mode: 0400
    owner: "{{ kafka_user }}"
    group: "{{ kafka_group }}"
  register: kafka_config

- name: Copy Log4j Properties
  template:
    src: log4j.properties.j2
    dest: "{{ kafka_etc_dir }}/log4j.properties"
    mode: 0400
    owner: "{{ kafka_user }}"
    group: "{{ kafka_group }}"
  register: kafka_log4j_config
